version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even though it's the weekly default
      time: "07:00" # UTC
  - package-ecosystem: "npm"
    directories:
      - "/js"
      - "/polyfills"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even though it's the weekly default
      time: "07:00" # UTC
    ignore:
      - dependency-name: "@gatling.io/*"
      # the major version for Node should match the minimum version required in the documentation
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "npm"
    directories:
      - "/js-simulation"
      - "/ts-simulation"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
      day: "monday" # explicit, even though it's the weekly default
      time: "07:00" # UTC
    ignore:
      - dependency-name: "@gatling.io/*"
