version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/js"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: "@gatling.io/*"
      # the major version for Node should match the minimum version required in the documentation
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "npm"
    directory: "/js-simulation"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: "@gatling.io/*"
  - package-ecosystem: "npm"
    directory: "/ts-simulation"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
      day: "sunday"
    ignore:
      - dependency-name: "@gatling.io/*"
