name: "Build and upload bundle"
description: "Build bundle (GraalVM + JVM dependencies) and upload it to a GitHub release"
inputs:
  version:
    description: "Gatling JS version"
    required: true
  release-id:
    description: "ID of the GitHub release"
    required: true
  os-type:
    description: "Linux|Darwin|Windows_NT"
    required: true
  os-arch:
    description: "x64|arm64"
    required: true
  github-token:
    description: "Token used to upload file to the GitHub release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Generate version file
      shell: bash
      run: |
        echo 'export const versions = { graalvm: { jdk: "23.0.0", js: "24.1.1" }, java: { compilerRelease: "21" }, gatling: {core: "3.13.1", enterprisePluginCommons: "1.9.8",jsAdapter: "${{ inputs.version }}"}};' > js/bundle/src/versions.ts
    - name: Build bundle
      shell: bash
      working-directory: ./js
      run: |
        echo "architecture: $(arch)"
        npm ci
        npm version "${{ inputs.version }}"
        npm run generate --workspace=bundle
        curl --location --silent --show-error \
          --connect-timeout 10 \
          --max-time 300 \
          --request POST \
          --header "Accept: application/vnd.github+json" \
          --header "Authorization: Bearer ${{ inputs.github-token }}" \
          --header "X-GitHub-Api-Version: 2022-11-28" \
          --header "Content-Type: application/octet-stream" \
          "https://uploads.github.com/repos/gatling/gatling-js/releases/188962826/assets?name=gatling-js-bundle-${{ inputs.version }}-${{ inputs.os-type }}-${{ inputs.os-arch }}.zip" \
          --data-binary "@bundle/tmp/gatling-js-bundle-${{ inputs.version }}-${{ inputs.os-type }}-${{ inputs.os-arch }}.zip"
