import { ProtocolBuilder } from "@gatling.io/core";

import { GrpcServerConfigurationBuilder, wrapGrpcServerConfigurationBuilder } from "./serverConfiguration";

import JvmGrpcProtocolBuilder = io.gatling.javaapi.grpc.GrpcProtocolBuilder;

export interface GrpcProtocolBuilder extends ProtocolBuilder {
  // Server configurations
  serverConfiguration(serverConfigurationName: string): GrpcServerConfigurationBuilder;
  serverConfigurations(...serverConfigurations: GrpcServerConfigurationBuilder[]): GrpcProtocolBuilder;
}

export const wrapGrpcProtocolBuilder = (_underlying: JvmGrpcProtocolBuilder): GrpcProtocolBuilder => ({
  _underlying,
  // Server configurations
  serverConfiguration: (serverConfigurationName) =>
    wrapGrpcServerConfigurationBuilder(_underlying.serverConfiguration(serverConfigurationName)),
  serverConfigurations: (...serverConfigurations) =>
    wrapGrpcProtocolBuilder(_underlying.serverConfigurations(serverConfigurations.map((config) => config._underlying)))
});

export const grpcProtocolBuilder = wrapGrpcProtocolBuilder(
  // GrpcDsl.grpc doesn't get properly generated by java2ts because of conflicts with methods of the same name
  Java.type<any>("io.gatling.javaapi.grpc.GrpcDsl").grpc
);
