/*
 * Copyright 2011-2025 GatlingCorp (https://gatling.io)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

@Java2TS(
    declare = {
        // ********** java **********
        @Type(value = java.lang.System.class, export = true),
        // java.time
        @Type(value = java.time.Duration.class, export = true),
        @Type(value = java.time.temporal.ChronoUnit.class, export = true),
        @Type(value = java.time.temporal.TemporalUnit.class, export = true),
        // ********** core **********
        @Type(value = io.gatling.javaapi.core.CoreDsl.class, export = true),
        @Type(value = io.gatling.javaapi.core.ActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.core.Assertion.class, export = true),
        @Type(value = io.gatling.javaapi.core.Assertion.WithPath.class, export = true),
        @Type(value = io.gatling.javaapi.core.Assertion.WithPathAndTimeMetric.class, export = true),
        @Type(value = io.gatling.javaapi.core.Assertion.WithPathAndCountMetric.class, export = true),
        @Type(value = io.gatling.javaapi.core.Assertion.WithPathAndTarget.class, export = true),
        @Type(value = io.gatling.javaapi.core.Body.class, export = true),
        @Type(value = io.gatling.javaapi.core.Body.WithBytes.class, export = true),
        @Type(value = io.gatling.javaapi.core.Body.WithString.class, export = true),
        @Type(value = io.gatling.javaapi.core.ChainBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.core.CheckBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.core.CheckBuilder.CaptureGroupCheckBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.core.CheckBuilder.Final.class, export = true),
        @Type(value = io.gatling.javaapi.core.CheckBuilder.Find.class, export = true),
        @Type(value = io.gatling.javaapi.core.CheckBuilder.JsonOfTypeFind.class, export = true),
        @Type(value = io.gatling.javaapi.core.CheckBuilder.JsonOfTypeMultipleFind.class, export = true),
        @Type(value = io.gatling.javaapi.core.CheckBuilder.MultipleFind.class, export = true),
        @Type(value = io.gatling.javaapi.core.CheckBuilder.Validate.class, export = true),
        @Type(value = io.gatling.javaapi.core.Choice.class, export = true),
        @Type(value = io.gatling.javaapi.core.Choice.WithKey.class, export = true),
        @Type(value = io.gatling.javaapi.core.Choice.WithKey.Then.class, export = true),
        @Type(value = io.gatling.javaapi.core.Choice.WithWeight.class, export = true),
        @Type(value = io.gatling.javaapi.core.Choice.WithWeight.Then.class, export = true),
        @Type(value = io.gatling.javaapi.core.ClosedInjectionStep.class, export = true),
        @Type(value = io.gatling.javaapi.core.ClosedInjectionStep.Constant.class, export = true),
        @Type(value = io.gatling.javaapi.core.ClosedInjectionStep.Ramp.class, export = true),
        @Type(value = io.gatling.javaapi.core.ClosedInjectionStep.RampTo.class, export = true),
        @Type(value = io.gatling.javaapi.core.ClosedInjectionStep.Stairs.class, export = true),
        @Type(value = io.gatling.javaapi.core.ClosedInjectionStep.StairsWithTime.class, export = true),
        @Type(value = io.gatling.javaapi.core.ClosedInjectionStep.Composite.class, export = true),
        @Type(value = io.gatling.javaapi.core.DummyBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.core.FeederBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.core.FeederBuilder.FileBased.class, export = true),
        @Type(value = io.gatling.javaapi.core.FeederBuilder.Batchable.class, export = true),
        @Type(value = io.gatling.javaapi.core.Filter.class, export = true),
        @Type(value = io.gatling.javaapi.core.Filter.AllowList.class, export = true),
        @Type(value = io.gatling.javaapi.core.Filter.DenyList.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.Ramp.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.StressPeak.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.ConstantRate.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.ConstantRate.ConstantRateOpenInjectionStep.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.RampRate.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.RampRate.During.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.RampRate.RampRateOpenInjectionStep.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.Stairs.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.Stairs.Times.class, export = true),
        @Type(value = io.gatling.javaapi.core.OpenInjectionStep.Stairs.Composite.class, export = true),
        @Type(value = io.gatling.javaapi.core.PauseType.class, export = true),
        @Type(value = io.gatling.javaapi.core.PauseType.NormalWithPercentageDuration.class, export = true),
        @Type(value = io.gatling.javaapi.core.PauseType.NormalWithStdDevDuration.class, export = true),
        @Type(value = io.gatling.javaapi.core.PauseType.Custom.class, export = true),
        @Type(value = io.gatling.javaapi.core.PauseType.UniformPercentage.class, export = true),
        @Type(value = io.gatling.javaapi.core.PauseType.UniformDuration.class, export = true),
        @Type(value = io.gatling.javaapi.core.PopulationBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.core.ProtocolBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.core.ScenarioBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.core.Session.class, export = true),
        @Type(value = io.gatling.javaapi.core.Simulation.class, export = true),
        @Type(value = io.gatling.javaapi.core.Simulation.SetUp.class, export = true),
        @Type(value = io.gatling.javaapi.core.StructureBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.core.ThrottleStep.class, export = true),
        @Type(value = io.gatling.javaapi.core.ThrottleStep.ReachIntermediate.class, export = true),
        // core.condition
        @Type(value = io.gatling.javaapi.core.condition.DoIf.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoIf.Then.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoIfEquals.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoIfEquals.Then.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoIfEqualsOrElse.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoIfEqualsOrElse.Then.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoIfOrElse.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoIfOrElse.Then.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoIfOrElse.OrElse.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoSwitch.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoSwitch.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoSwitchOrElse.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoSwitchOrElse.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.DoSwitchOrElse.OrElse.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.RandomSwitch.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.RandomSwitch.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.RandomSwitchOrElse.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.RandomSwitchOrElse.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.RandomSwitchOrElse.OrElse.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.RoundRobinSwitch.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.RoundRobinSwitch.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.UniformRandomSwitch.class, export = true),
        @Type(value = io.gatling.javaapi.core.condition.UniformRandomSwitch.On.class, export = true),
        // core.error
        @Type(value = io.gatling.javaapi.core.error.Errors.class, export = true),
        @Type(value = io.gatling.javaapi.core.error.Errors.ExitBlockOnFail.class, export = true),
        @Type(value = io.gatling.javaapi.core.error.Errors.TryMax.class, export = true),
        // core.exec
        @Type(value = io.gatling.javaapi.core.exec.Execs.class, export = true),
        @Type(value = io.gatling.javaapi.core.exec.Executable.class, export = true),
        // core.feed
        @Type(value = io.gatling.javaapi.core.feed.Feeds.class, export = true),
        // core.group
        @Type(value = io.gatling.javaapi.core.group.Groups.class, export = true),
        @Type(value = io.gatling.javaapi.core.group.Groups.On.class, export = true),
        // core.loop
        @Type(value = io.gatling.javaapi.core.loop.AsLongAs.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.AsLongAs.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.AsLongAsDuring.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.AsLongAsDuring.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.DoWhile.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.DoWhile.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.DoWhileDuring.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.DoWhileDuring.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.During.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.During.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.ForEach.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.ForEach.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.Forever.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.Forever.On.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.Repeat.class, export = true),
        @Type(value = io.gatling.javaapi.core.loop.Repeat.On.class, export = true),
        // core.pause
        @Type(value = io.gatling.javaapi.core.pause.Paces.class, export = true),
        @Type(value = io.gatling.javaapi.core.pause.Pauses.class, export = true),
        @Type(value = io.gatling.javaapi.core.pause.RendezVous.class, export = true),
        // ********** http **********
        @Type(value = io.netty.handler.codec.http.HttpHeaders.class, export = true),
        @Type(value = io.netty.handler.codec.http.HttpResponseStatus.class, export = true),
        @Type(value = io.netty.handler.codec.http.cookie.Cookie.class, export = true),
        @Type(value = io.gatling.http.client.Request.class, export = true),
        @Type(value = io.gatling.http.client.body.RequestBody.class, export = true),
        @Type(value = io.gatling.http.response.Response.class, export = true),
        @Type(value = io.gatling.http.response.ResponseBody.class, export = true),
        @Type(value = io.gatling.javaapi.http.AddCookie.class, export = true),
        @Type(value = io.gatling.javaapi.http.BodyPart.class, export = true),
        @Type(value = io.gatling.javaapi.http.GetCookie.class, export = true),
        @Type(value = io.gatling.javaapi.http.Http.class, export = true),
        @Type(value = io.gatling.javaapi.http.HttpDsl.class, export = true),
        @Type(value = io.gatling.javaapi.http.HttpProtocolBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.http.HttpProtocolBuilder.TypedCondition.class, export = true),
        @Type(value = io.gatling.javaapi.http.HttpProtocolBuilder.UntypedCondition.class, export = true),
        @Type(value = io.gatling.javaapi.http.HttpRequestActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.http.Polling.class, export = true),
        @Type(value = io.gatling.javaapi.http.Polling.Every.class, export = true),
        @Type(value = io.gatling.javaapi.http.Proxy.class, export = true),
        @Type(value = io.gatling.javaapi.http.RequestActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.http.RequestWithBodyActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.http.Sse.class, export = true),
        @Type(value = io.gatling.javaapi.http.Sse.Prefix.class, export = true),
        @Type(value = io.gatling.javaapi.http.SseAwaitActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.http.SseAwaitActionBuilder.On.class, export = true),
        @Type(value = io.gatling.javaapi.http.SseConnectActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.http.SseMessageCheck.class, export = true),
        @Type(value = io.gatling.javaapi.http.SseMessageCheck.TypedCondition.class, export = true),
        @Type(value = io.gatling.javaapi.http.SseMessageCheck.UntypedCondition.class, export = true),
        @Type(value = io.gatling.javaapi.http.SseSetCheckActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.http.Ws.class, export = true),
        @Type(value = io.gatling.javaapi.http.Ws.Prefix.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsAwaitActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsAwaitActionBuilder.On.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsFrameCheck.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsFrameCheck.Binary.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsFrameCheck.Binary.UntypedCondition.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsFrameCheck.Binary.TypedCondition.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsFrameCheck.Text.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsFrameCheck.Text.UntypedCondition.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsFrameCheck.Text.TypedCondition.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsConnectActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsSendBinaryActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.http.WsSendTextActionBuilder.class, export = true),
        // ********** grpc **********
        @Type(value = com.google.protobuf.Descriptors.Descriptor.class, export = true),
        @Type(value = com.google.protobuf.DynamicMessage.Builder.class, export = true),
        @Type(value = io.grpc.CallCredentials.class, export = true),
        @Type(value = io.grpc.CallOptions.class, export = true),
        @Type(value = io.grpc.ChannelCredentials.class, export = true),
        @Type(value = io.grpc.Metadata.class, export = true),
        @Type(value = io.grpc.Metadata.AsciiMarshaller.class, export = true),
        @Type(value = io.grpc.Metadata.BinaryMarshaller.class, export = true),
        @Type(value = io.grpc.Metadata.Key.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.Grpc.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcBidiStreamAwaitStreamEndActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcBidirectionalStreamingServiceBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcClientStreamAwaitStreamEndActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcClientStreamingServiceBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcDsl.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcDsl.MessageResponseTimePolicy.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcHeaders.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcHeaders.Value.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcProtocolBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcServerStreamAwaitStreamEndActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcServerStreamStreamSendActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcServerStreamingServiceBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcUnaryActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.grpc.GrpcUnaryServiceBuilder.class, export = true),
        // ********** mqtt **********
        @Type(value = io.netty.handler.codec.mqtt.MqttFixedHeader.class, export = true),
        @Type(value = io.netty.handler.codec.mqtt.MqttMessageType.class, export = true),
        @Type(value = io.netty.handler.codec.mqtt.MqttPublishVariableHeader.class, export = true),
        @Type(value = io.netty.handler.codec.mqtt.MqttProperties.class, export = true),
        @Type(value = io.netty.handler.codec.mqtt.MqttQoS.class, export = true),
        @Type(value = io.gatling.mqtt.action.MqttInboundMessage.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.ConnectActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.LastWillBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.Mqtt.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.MqttBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.MqttDsl.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.MqttProtocolBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.PublishActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.PublishActionBuilder.Base.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.PublishActionBuilder.Checkable.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.SubscribeActionBuilder.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.SubscribeActionBuilder.Checkable.class, export = true),
        @Type(value = io.gatling.javaapi.mqtt.WaitForMessagesActionBuilder.class, export = true)
    })
package io.gatling.javaapi;

import org.bsc.processor.annotation.Java2TS;
import org.bsc.processor.annotation.Type;
