import { Expression, Session, underlyingSessionTo } from "@gatling.io/core";

import { GraphQlJsonScope, wrapGraphQlJsonScope } from "./jsonScope";
import { GraphQlProtocolBuilder, wrapGraphQlProtocolBuilder } from "./protocol";
import {
  GraphQlDynamicRequestActionBuilder,
  GraphQlRequestActionBuilder,
  wrapGraphQlDynamicRequestActionBuilder,
  wrapGraphQlRequestActionBuilder
} from "./request";
import { GraphQlWs, wrapGraphQlWs } from "./ws";

export * from "./jsonScope";
export * from "./protocol";
export * from "./request";
export * from "./variables";
export * from "./ws";

import { GraphQlDsl as JvmGraphQlDsl } from "@gatling.io/jvm-types";

import JvmGraphQl = io.gatling.javaapi.graphql.GraphQl;
import JvmGraphQlJsonScope = io.gatling.javaapi.graphql.GraphQlJsonScope;
import JvmGraphQlWs = io.gatling.javaapi.graphql.GraphQlWs;

// static fields aren't generated by java2ts
const jvmGraphQlDsl = JvmGraphQlDsl as any;
const jvmGraphQl: JvmGraphQl = jvmGraphQlDsl.graphql;

/**
 * The entrypoint of the GraphQL DSL, for queries and mutations sent over HTTP
 */
export interface GraphQl extends Pick<
  GraphQlProtocolBuilder,
  | "endpoint"
  | "wsEndpoint"
  | "failOnErrors"
  | "failOnDataNull"
  | "ignoreErrors"
  | "requireNamedOperations"
  | "queriesOverGet"
  | "automaticPersistedQueries"
  | "automaticPersistedQueriesOverGet"
  | "sharePersistedQueries"
> {
  /**
   * Bootstrap a query, the document is validated to be a query when the simulation is built
   *
   * @param document - the query document
   * @returns the next DSL step
   */
  query(document: string): GraphQlRequestActionBuilder;

  /**
   * Bootstrap a mutation, the document is validated to be a mutation when the simulation is built
   *
   * @param document - the mutation document
   * @returns the next DSL step
   */
  mutation(document: string): GraphQlRequestActionBuilder;

  /**
   * Bootstrap an operation whose document is loaded from a file
   *
   * @param filePath - the path of the file, in the resources folder
   * @returns the next DSL step
   */
  file(filePath: string): GraphQlRequestActionBuilder;

  /**
   * Bootstrap an operation of any type
   *
   * @param document - the document
   * @returns the next DSL step
   */
  document(document: string): GraphQlRequestActionBuilder;

  /**
   * Bootstrap an operation whose document is only known at runtime, eg from a feeder. The document
   * isn't parsed when the simulation is built, so the request must be named explicitly. This name is
   * only used in the statistics: use operationName() to send an operation name in the request payload.
   *
   * @param requestName - the request name, expressed as a Gatling Expression Language String
   * @param document - the document, expressed as a Gatling Expression Language String
   * @returns the next DSL step
   */
  dynamicDocument(requestName: string, document: string): GraphQlDynamicRequestActionBuilder;

  /**
   * Bootstrap an operation whose document is only known at runtime, eg from a feeder. The document
   * isn't parsed when the simulation is built, so the request must be named explicitly. This name is
   * only used in the statistics: use operationName() to send an operation name in the request payload.
   *
   * @param requestName - the request name, expressed as a Gatling Expression Language String
   * @param document - the document, expressed as a function
   * @returns the next DSL step
   */
  dynamicDocument(requestName: string, document: (session: Session) => string): GraphQlDynamicRequestActionBuilder;

  /**
   * Bootstrap an operation whose document is only known at runtime, eg from a feeder. The document
   * isn't parsed when the simulation is built, so the request must be named explicitly. This name is
   * only used in the statistics: use operationName() to send an operation name in the request payload.
   *
   * @param requestName - the request name, expressed as a function
   * @param document - the document, expressed as a Gatling Expression Language String
   * @returns the next DSL step
   */
  dynamicDocument(requestName: (session: Session) => string, document: string): GraphQlDynamicRequestActionBuilder;

  /**
   * Bootstrap an operation whose document is only known at runtime, eg from a feeder. The document
   * isn't parsed when the simulation is built, so the request must be named explicitly. This name is
   * only used in the statistics: use operationName() to send an operation name in the request payload.
   *
   * @param requestName - the request name, expressed as a function
   * @param document - the document, expressed as a function
   * @returns the next DSL step
   */
  dynamicDocument(
    requestName: (session: Session) => string,
    document: (session: Session) => string
  ): GraphQlDynamicRequestActionBuilder;
}

const dynamicDocument = (requestName: Expression<string>, document: Expression<string>) => {
  if (typeof requestName === "function") {
    return typeof document === "function"
      ? jvmGraphQl.dynamicDocument(underlyingSessionTo(requestName), underlyingSessionTo(document))
      : jvmGraphQl.dynamicDocument(underlyingSessionTo(requestName), document);
  } else {
    return typeof document === "function"
      ? jvmGraphQl.dynamicDocument(requestName, underlyingSessionTo(document))
      : jvmGraphQl.dynamicDocument(requestName, document);
  }
};

/**
 * The entrypoint of the GraphQL DSL, for queries and mutations sent over HTTP
 */
export const graphql: GraphQl = {
  endpoint: (endpoint: Expression<string>) =>
    wrapGraphQlProtocolBuilder(
      typeof endpoint === "function"
        ? jvmGraphQl.endpoint(underlyingSessionTo(endpoint))
        : jvmGraphQl.endpoint(endpoint)
    ),
  wsEndpoint: (endpoint: Expression<string>) =>
    wrapGraphQlProtocolBuilder(
      typeof endpoint === "function"
        ? jvmGraphQl.wsEndpoint(underlyingSessionTo(endpoint))
        : jvmGraphQl.wsEndpoint(endpoint)
    ),
  failOnErrors: () => wrapGraphQlProtocolBuilder(jvmGraphQl.failOnErrors()),
  failOnDataNull: () => wrapGraphQlProtocolBuilder(jvmGraphQl.failOnDataNull()),
  ignoreErrors: () => wrapGraphQlProtocolBuilder(jvmGraphQl.ignoreErrors()),
  requireNamedOperations: () => wrapGraphQlProtocolBuilder(jvmGraphQl.requireNamedOperations()),
  queriesOverGet: () => wrapGraphQlProtocolBuilder(jvmGraphQl.queriesOverGet()),
  automaticPersistedQueries: () => wrapGraphQlProtocolBuilder(jvmGraphQl.automaticPersistedQueries()),
  automaticPersistedQueriesOverGet: () => wrapGraphQlProtocolBuilder(jvmGraphQl.automaticPersistedQueriesOverGet()),
  sharePersistedQueries: () => wrapGraphQlProtocolBuilder(jvmGraphQl.sharePersistedQueries()),
  query: (document: string) => wrapGraphQlRequestActionBuilder(jvmGraphQl.query(document)),
  mutation: (document: string) => wrapGraphQlRequestActionBuilder(jvmGraphQl.mutation(document)),
  file: (filePath: string) => wrapGraphQlRequestActionBuilder(jvmGraphQl.file(filePath)),
  document: (document: string) => wrapGraphQlRequestActionBuilder(jvmGraphQl.document(document)),
  dynamicDocument: (requestName: Expression<string>, document: Expression<string>) =>
    wrapGraphQlDynamicRequestActionBuilder(dynamicDocument(requestName, document))
};

/**
 * The entrypoint of the GraphQL subscriptions DSL, sent over WebSocket with the graphql-transport-ws protocol
 */
export const graphqlWs: GraphQlWs = wrapGraphQlWs(jvmGraphQlDsl.graphqlWs as JvmGraphQlWs);

/**
 * Scope for checks on the data of GraphQL responses
 */
export const graphqlData: GraphQlJsonScope = wrapGraphQlJsonScope(jvmGraphQlDsl.graphqlData as JvmGraphQlJsonScope);

/**
 * Scope for checks on the errors of GraphQL responses
 */
export const graphqlErrors: GraphQlJsonScope = wrapGraphQlJsonScope(jvmGraphQlDsl.graphqlErrors as JvmGraphQlJsonScope);

/**
 * Scope for checks on the extensions of GraphQL responses
 */
export const graphqlExtensions: GraphQlJsonScope = wrapGraphQlJsonScope(
  jvmGraphQlDsl.graphqlExtensions as JvmGraphQlJsonScope
);
