name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      JAVA_OPTS: "-Xmx4G"
      SBT_OPTS: "-Dsbt.ci=true"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Set up sbt
        uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24

      - name: Build JS polyfills
        working-directory: ./polyfills
        run: |
          npm ci
          npm run format-check
          npm run build

      - name: Build JVM projects
        working-directory: ./jvm
        run: |
          sbt \
            "project gatling-jvm-to-js-adapter" \
            headerCheckAll \
            javafmtCheckAll \
            scalafmtCheckAll \
            "scalafixAll --check" \
            compile \
            test

      - name: Build JS projects
        working-directory: ./js
        run: |
          npm ci
          npm run format-check --workspaces
          npm run build --workspaces
